name: NodeJS

on:
  push:
    branches: ['**']

jobs:

  complete:
    if: always()
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: exit 1

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 22.6.0
        cache: 'npm'
    - run: npm ci
    - run: npm run prettier:check
    - run: npm run biome:check
