name: "Rust: Build & test"

on:
  push:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown
      - name: Run tests
        run: cargo test --verbose
