name: "Rust: Build & test"

on:
  push:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: make build

      - name: Run tests
        run: cargo test --verbose

      - name: Run clippy
        run: cargo clippy -- -D warnings
